# Austin, Travis County Zillow Recession Analysis

Despite a global pandemic in COVID-19 that rocked global markets in 2020, dropping them between 20-25%, Texas, especially Austin, saw a dramatic increase in housing prices. Employees realized that they aren't confined to a certain geographic location in order to finish their work, which spiked Airbnb bookings. Given low interest rates from the Federal Reserve to boost a tumbling economy, along with out of state migration and investment interest from California and New York, Texas and Austin real estate prices shot to the moon. This bullish market lasted through 2021, but with the Fed increasing interest rates to tame inflation in 2022, some suspect an upcoming recession. This application is designed to work on the same dataset as the zillow_data_analysis.ipynb file, but instead trains a linear regression model on the Great Recession of December 2007-June 2009. Then the model is tested against April 2022 - June 2022 data to see it's validity and usability. 

## Data Import, Processing and Visualization

In [9]:
# Import statements

import pandas as pd
from pathlib import Path
import hvplot.pandas
import numpy as np
import math

In [10]:
# Import Zillow dataset into a pandas dataframe and display said data

zillow_df = pd.read_csv(Path('Resources/zillow_home_values.csv'),
                        infer_datetime_format=True)

display(zillow_df.head())

RegionID  SizeRank  RegionName RegionType StateName State      City  \
0     61639         0       10025        Zip        NY    NY  New York   
1     84654         1       60657        Zip        IL    IL   Chicago   
2     61637         2       10023        Zip        NY    NY  New York   
3     91982         3       77494        Zip        TX    TX      Katy   
4     84616         4       60614        Zip        IL    IL   Chicago   

                              Metro       CountyName  01/31/2000  ...  \
0       New York-Newark-Jersey City  New York County    324383.0  ...   
1          Chicago-Naperville-Elgin      Cook County    313500.0  ...   
2       New York-Newark-Jersey City  New York County    506994.0  ...   
3  Houston-The Woodlands-Sugar Land    Harris County    224938.0  ...   
4          Chicago-Naperville-Elgin      Cook County    409547.0  ...   

   09/30/2021  10/31/2021  11/30/2021  12/31/2021  01/31/2022  02/28/2022  \
0   1132221.0   1136610.0   1135991.0   1136561.0   1142452.0   1154203.0   
1    524133.0    526722.0    529521.0    531520.0    532909.0    533123.0   
2   1498926.0   1507590.0   1511855.0   1512170.0   1522793.0   1532550.0   
3    421500.0    429474.0    436571.0    442317.0    448423.0    457973.0   
4    668926.0    672856.0    677523.0    680459.0    682380.0    682141.0   

   03/31/2022  04/30/2022  05/31/2022  06/30/2022  
0   1172911.0   1189572.0   1203675.0   1209322.0  
1    535804.0    537898.0    542946.0    546766.0  
2   1549563.0   1562744.0   1581340.0   1590483.0  
3    469673.0    483460.0    494924.0    502464.0  
4    685249.0    687700.0    693521.0    698444.0  

[5 rows x 279 columns]

In [11]:
# Splice for only Austin data

zillow_austin = zillow_df.loc[zillow_df['Metro'] == 'Austin-Round Rock']
zillow_austin_df = zillow_austin.loc[zillow_austin['City'] == 'Austin']
display(zillow_austin_df.head())

RegionID  SizeRank  RegionName RegionType StateName State    City  \
70        92617        71       78704        Zip        TX    TX  Austin   
92        92654        93       78745        Zip        TX    TX  Austin   
443       92657       446       78748        Zip        TX    TX  Austin   
450       92667       453       78758        Zip        TX    TX  Austin   
485       92651       488       78741        Zip        TX    TX  Austin   
520       92662       523       78753        Zip        TX    TX  Austin   
594       92668       597       78759        Zip        TX    TX  Austin   
1604      92653      1617       78744        Zip        TX    TX  Austin   
2060      92634      2075       78723        Zip        TX    TX  Austin   
2157      92658      2172       78749        Zip        TX    TX  Austin   
2404      92640      2421       78729        Zip        TX    TX  Austin   
2639      92628      2661       78717        Zip        TX    TX  Austin   
2780      92638      2801       78727        Zip        TX    TX  Austin   
2983      92642      3007       78731        Zip        TX    TX  Austin   
3378      92618      3411       78705        Zip        TX    TX  Austin   
3508      92639      3542       78728        Zip        TX    TX  Austin   
3700      92655      3735       78746        Zip        TX    TX  Austin   
3772      92616      3809       78703        Zip        TX    TX  Austin   
3957      92659      3993       78750        Zip        TX    TX  Austin   
4132      92615      4172       78702        Zip        TX    TX  Austin   
4218      92666      4260       78757        Zip        TX    TX  Austin   
5118      92646      5168       78735        Zip        TX    TX  Austin   
5288      92663      5338       78754        Zip        TX    TX  Austin   
5397      92660      5450       78751        Zip        TX    TX  Austin   
5638      92661      5693       78752        Zip        TX    TX  Austin   
6437      92635      6499       78724        Zip        TX    TX  Austin   
6792      92656      6859       78747        Zip        TX    TX  Austin   
6809      92555      6876       78617        Zip        TX    TX  Austin   
7048      92648      7119       78737        Zip        TX    TX  Austin   
7279      92650      7354       78739        Zip        TX    TX  Austin   
7323      92614      7401       78701        Zip        TX    TX  Austin   
7402      92637      7479       78726        Zip        TX    TX  Austin   
7445      92643      7526       78732        Zip        TX    TX  Austin   
9247      92665      9358       78756        Zip        TX    TX  Austin   
9515      92632      9629       78721        Zip        TX    TX  Austin   
9728      92641      9846       78730        Zip        TX    TX  Austin   
9902      92647     10021       78736        Zip        TX    TX  Austin   
10839     92636     10974       78725        Zip        TX    TX  Austin   
10942     92644     11082       78733        Zip        TX    TX  Austin   
10987     92633     11128       78722        Zip        TX    TX  Austin   
12423     92585     12602       78652        Zip        TX    TX  Austin   
21376     92630     22577       78719        Zip        TX    TX  Austin   
23803     92652     25635       78742        Zip        TX    TX  Austin   

                   Metro     CountyName  01/31/2000  ...  09/30/2021  \
70     Austin-Round Rock  Travis County    258755.0  ...    950810.0   
92     Austin-Round Rock  Travis County    158425.0  ...    541850.0   
443    Austin-Round Rock  Travis County    168963.0  ...    498905.0   
450    Austin-Round Rock  Travis County    128102.0  ...    497849.0   
485    Austin-Round Rock  Travis County    147654.0  ...    456450.0   
520    Austin-Round Rock  Travis County    129273.0  ...    438699.0   
594    Austin-Round Rock  Travis County    253680.0  ...    763853.0   
1604   Austin-Round Rock  Travis County    120228.0  ...    401862.0   
2060   Austin-

In [12]:
# Create a dataframe with only the dates as the rows and zip codes as the columns with the prices as the primary data

dates_df = zillow_austin_df.drop(columns=['RegionID', 'RegionName','RegionType','State', 'City', 'Metro', 'CountyName', 'SizeRank','StateName']).T
zipcode_df = zillow_austin_df['RegionName']

dates_df.set_index(dates_df.columns[0])
dates_df.columns = zipcode_df

display(dates_df)

RegionName      78704     78745     78748     78758     78741     78753  \
01/31/2000   258755.0  158425.0  168963.0  128102.0  147654.0  129273.0   
02/29/2000   263523.0  158246.0  169557.0  128616.0  149019.0  129699.0   
03/31/2000   268348.0  159585.0  170277.0  129124.0  149457.0  129880.0   
04/30/2000   272660.0  160477.0  171529.0  130212.0  149806.0  130571.0   
05/31/2000   276739.0  160869.0  172626.0  130949.0  149329.0  131124.0   
...               ...       ...       ...       ...       ...       ...   
02/28/2022  1053418.0  589353.0  541130.0  537845.0  496936.0  474259.0   
03/31/2022  1072684.0  602249.0  553220.0  551156.0  508005.0  485392.0   
04/30/2022  1087691.0  612028.0  561694.0  561618.0  515889.0  494108.0   
05/31/2022  1096965.0  618316.0  568101.0  567226.0  519962.0  500128.0   
06/30/2022  1095829.0  613862.0  563042.0  560180.0  514218.0  495392.0   

RegionName     78759     78744     78723     78749  ...     78756     78721  \
01/31/2000  253680.0  120228.0  156793.0  207483.0  ...  296389.0  138992.0   
02/29/2000  255556.0  120856.0  159300.0  206991.0  ...  304238.0  140029.0   
03/31/2000  257186.0  121483.0  164323.0  206529.0  ...  305509.0  142717.0   
04/30/2000  259497.0  122325.0  167621.0  205803.0  ...  310970.0  147868.0   
05/31/2000  260554.0  123007.0  170671.0  205134.0  ...  311430.0  154022.0   
...              ...       ...       ...       ...  ...       ...       ...   
02/28/2022  844218.0  440666.0  652733.0  686617.0  ...  931114.0  559595.0   
03/31/2022  862457.0  451566.0  663550.0  701109.0  ...  944235.0  571327.0   
04/30/2022  876764.0  460693.0  670097.0  713245.0  ...  952069.0  576838.0   
05/31/2022  884352.0  467861.0  672464.0  721249.0  ...  957718.0  579854.0   
06/30/2022  874722.0  464934.0  661809.0  713630.0  ...  950845.0  570825.0   

RegionName      78730     78736     78725      78733     78722     78652  \
01/31/2000   488050.0  223100.0  120213.0   438890.0       NaN  192614.0   
02/29/2000   487684.0  222703.0  120984.0   438804.0       NaN  193082.0   
03/31/2000   489031.0  223886.0  121723.0   439757.0       NaN  194118.0   
04/30/2000   491682.0  224554.0  123021.0   441868.0       NaN  195968.0   
05/31/2000   494572.0  224520.0  124149.0   441903.0       NaN  197784.0   
...               ...       ...       ...        ...       ...       ...   
02/28/2022  1346091.0  721532.0  388065.0  1397156.0  741936.0  595321.0   
03/31/2022  1385862.0  736466.0  398068.0  1431161.0  760522.0  610890.0   
04/30/2022  1421492.0  748991.0  407091.0  1465264.0  773833.0  624577.0   
05/31/2022  1447688.0  757909.0  415376.0  1487102.0  787315.0  632163.0   
06/30/2022  1443527.0  751814.0  414398.0  1490228.0  779648.0  624738.0   

RegionName     78719     78742  
01/31/2000  144311.0  117246.0  
02/29/2000  145057.0  117515.0  
03/31/2000  144970.0  116911.0  
04/30/2000  145948.0  116133.0  
05/31/2000  146070.0  114755.0  
...              ...       ...  
02/28/2022  415204.0  424746.0  
03/31/2022  427896.0  434459.0  
04/30/2022  439443.0  441220.0  
05/31/2022  448147.0  447581.0  
06/30/2022  443553.0  443758.0  

[270 rows x 43 columns]

In [13]:
# Plot Zillow data for all zip codes

dates_df.hvplot.line(rot=90, 
    xlabel="Dates",
    ylabel="Average Home Prices",
    width=2500, 
    height=600
).opts(yformatter="%.0f")

:NdOverlay   [RegionName]
   :Curve   [index]   (value)

In [14]:
# Parse through and extract the Dec 2007 - June 2010 data 

recession_dates = dates_df.loc["11/30/2007":"06/30/2010", :]
display(recession_dates.head())

RegionName     78704     78745     78748     78758     78741     78753  \
11/30/2007  373165.0  189872.0  203840.0  156372.0  181694.0  159376.0   
12/31/2007  374997.0  190459.0  204525.0  156577.0  182941.0  159997.0   
01/31/2008  375049.0  190528.0  204625.0  156308.0  183026.0  160229.0   
02/29/2008  374256.0  190409.0  204437.0  155932.0  182415.0  160210.0   
03/31/2008  374282.0  190847.0  204827.0  155928.0  182422.0  160065.0   

RegionName     78759     78744     78723     78749  ...     78756     78721  \
11/30/2007  313919.0  152706.0  213829.0  240005.0  ...  362903.0  184876.0   
12/31/2007  315961.0  153375.0  214482.0  241460.0  ...  363836.0  185562.0   
01/31/2008  317099.0  153869.0  213949.0  242065.0  ...  365390.0  184115.0   
02/29/2008  318336.0  153644.0  214008.0  242037.0  ...  365745.0  183040.0   
03/31/2008  319758.0  153266.0  214708.0  242067.0  ...  366940.0  182252.0   

RegionName     78730     78736     78725     78733     78722     78652  \
11/30/2007  584038.0  273631.0  146513.0  534944.0  286480.0  232144.0   
12/31/2007  584989.0  274480.0  147557.0  535289.0  287711.0  234010.0   
01/31/2008  584975.0  274285.0  147759.0  533482.0  288514.0  235082.0   
02/29/2008  585169.0  274090.0  147375.0  531920.0  288146.0  234806.0   
03/31/2008  587389.0  273752.0  146900.0  531571.0  287985.0  236381.0   

RegionName     78719     78742  
11/30/2007  157543.0  152639.0  
12/31/2007  159036.0  153429.0  
01/31/2008  160748.0  153163.0  
02/29/2008  161033.0  153271.0  
03/31/2008  159892.0  153022.0  

[5 rows x 43 columns]

In [15]:
recession_dates.hvplot.line(rot=90, 
    xlabel="Dates",
    ylabel="Average Home Prices",
    width=2500, 
    height=600
).opts(yformatter="%.0f")

:NdOverlay   [RegionName]
   :Curve   [index]   (value)

In [16]:
    # in and out sample testing
    # inflation, certain president, migration, global pandemic, interest rates 
    # spin the story; If i'm going to buy now, why would this model work now

## Linear Regression Fitting to Data

In [17]:
# Apply linear regression from numpy to the dataset

months_elapsed = [num for num in np.arange(0, 960, 30)]

zip_fits = []
for (column_name, column_data) in recession_dates.iteritems():
    try:
        current_fit = np.polyfit(months_elapsed, recession_dates[column_name], 1)
        zip_fits.append(current_fit)
    except: 
        zip_fits.append(np.nan)
    finally: 
        continue

display(zip_fits)

[array([-4.09964260e+01,  3.81202932e+05]),
 array([-4.75259042e+00,  1.91203205e+05]),
 array([-7.95028104e+00,  2.04882818e+05]),
 array([-8.95136852e+00,  1.56383574e+05]),
 array([-2.76902859e+01,  1.85082358e+05]),
 array([-8.05429497e+00,  1.59240528e+05]),
 array([-2.19062256e+01,  3.22236364e+05]),
 array([-1.20281281e+01,  1.53444330e+05]),
 array([-1.0920534e+01,  2.1739033e+05]),
 array([-1.27989431e+01,  2.41718352e+05]),
 array([-1.49500244e+00,  2.01084426e+05]),
 array([-1.43293072e+01,  2.67401784e+05]),
 array([-3.69755621e+00,  1.98208551e+05]),
 array([-4.47920516e+01,  5.02081585e+05]),
 array([-3.41478067e+01,  2.41859449e+05]),
 array([-8.75610337e+00,  1.89319932e+05]),
 array([-5.06887891e+01,  7.74490506e+05]),
 array([-8.09461755e+01,  6.93138972e+05]),
 array([-6.34714687e+00,  2.80708767e+05]),
 array([-2.08873228e+01,  2.41930574e+05]),
 array([-1.64569098e+01,  2.85606494e+05]),
 array([-4.06347446e+01,  4.10985500e+05]),
 array([-2.38272727e+01,  1.962626

In [18]:
# Parse through the arrays and build 2 lists, one for the intercept and the other for the slope

linear_intercept = []
linear_slope = []

for arr in zip_fits:
    try:
        linear_slope.append(arr.tolist()[0])
        linear_intercept.append(arr.tolist()[1])
    except: 
        linear_slope.append(np.nan)
        linear_intercept.append(np.nan)
    finally: 
        continue

display(linear_intercept)
display(linear_slope)

[381202.93181818206,
 191203.2045454546,
 204882.8181818183,
 156383.57386363638,
 185082.35795454553,
 159240.52840909094,
 322236.3636363637,
 153444.32954545453,
 217390.32954545465,
 241718.35227272732,
 201084.4261363637,
 267401.7840909091,
 198208.55113636365,
 502081.5852272729,
 241859.44886363635,
 189319.93181818185,
 774490.5056818184,
 693138.9715909092,
 280708.76704545453,
 241930.57386363635,
 285606.4943181818,
 410985.50000000006,
 196262.61931818188,
 327895.45454545453,
 178343.32954545456,
 147987.5625,
 203483.65340909097,
 154060.48863636368,
 360848.72727272735,
 359962.81818181823,
 364336.6477272727,
 368899.1420454546,
 445759.6420454547,
 369375.04545454547,
 182853.26136363635,
 594651.7727272728,
 275639.4090909091,
 146884.19886363638,
 536666.0000000001,
 289561.7045454546,
 236311.77272727282,
 159172.23863636368,
 153147.25000000006]

[-40.99642595307934,
 -4.75259042033232,
 -7.950281036168187,
 -8.951368523949217,
 -27.69028592375374,
 -8.054294965786907,
 -21.906225562072454,
 -12.028128054740955,
 -10.920533968719516,
 -12.79894305962862,
 -1.4950024437928116,
 -14.329307184750729,
 -3.6975562072336103,
 -44.79205156402748,
 -34.14780669599212,
 -8.756103372434032,
 -50.688789100684254,
 -80.94617546432067,
 -6.3471468719452275,
 -20.88732282502443,
 -16.45690982404691,
 -40.63474462365588,
 -23.827272727272728,
 -32.41663611925707,
 -5.8186522482893475,
 -15.701075268817183,
 -23.113569159335373,
 -21.31872556207231,
 -32.31056940371455,
 -27.448130498533747,
 -72.28486070381233,
 -38.129472140762424,
 -57.903195259042164,
 -23.68907624633422,
 -35.84989002932547,
 -66.64850317693065,
 -25.442210410557184,
 -11.14437927663736,
 -55.065860215053775,
 -22.63236192570871,
 -13.934054252199534,
 -24.983913734115447,
 -24.431250000000034]

In [19]:
# Create a dataframe including the slope and intercept of the linear regression models for qualifying zip codes

zip_linear_fits_df = pd.DataFrame({
    'Zip Code': zipcode_df,
    'Slope': linear_slope,
    'Intercept': linear_intercept
})

zip_linear_fits_df.dropna(inplace=True)

zip_linear_fits_df.index = [num for num in np.arange(0, len(zip_linear_fits_df), 1)]

display(len(zip_linear_fits_df))
display(zip_linear_fits_df.head())
display(zip_linear_fits_df.tail())

43

Zip Code      Slope      Intercept
0     78704 -40.996426  381202.931818
1     78745  -4.752590  191203.204545
2     78748  -7.950281  204882.818182
3     78758  -8.951369  156383.573864
4     78741 -27.690286  185082.357955

Zip Code      Slope      Intercept
38     78733 -55.065860  536666.000000
39     78722 -22.632362  289561.704545
40     78652 -13.934054  236311.772727
41     78719 -24.983914  159172.238636
42     78742 -24.431250  153147.250000

## Validating/Testing Linear Regression Model

In [33]:
# Create new dataframe that includes the experimental and actual data values along with zip codes

last_three_months = [num for num in np.arange(0, 120, 30)]

actual_values_df = dates_df[zip_linear_fits_df['Zip Code']].iloc[-3:].T
actual_values_df.columns = ['04/30/2022 ($)', '05/31/2022 ($)', '06/30/2022 ($)']

experimental_values_df = pd.DataFrame()
experimental_values_df.index = ['04/30/2022 ($)', '05/31/2022 ($)', '06/30/2022 ($)']

num = 0
for model in linear_slope:
    if model == np.nan:
        continue
    else:
        april_price = round(linear_intercept[num] + model * last_three_months[0], 2)
        may_price = round(linear_intercept[num] + model * last_three_months[1], 2)
        june_price = round(linear_intercept[num] + model * last_three_months[2], 2)
        experimental_values_df[zip_linear_fits_df['Zip Code'].iloc[num]] = [april_price, may_price, june_price]
        num+=1

experimental_values_df = experimental_values_df.T


display(experimental_values_df)
display(actual_values_df)

# linear_percent_change = (data_prices - linear_prices)/data_prices * 100
# linear_percent_change = pd.Series(linear_percent_change)
# display(linear_percent_change.head())
# display(linear_percent_change.tail())


04/30/2022 ($)  05/31/2022 ($)  06/30/2022 ($)
78704       381202.93       379973.04       378743.15
78745       191203.20       191060.63       190918.05
78748       204882.82       204644.31       204405.80
78758       156383.57       156115.03       155846.49
78741       185082.36       184251.65       183420.94
78753       159240.53       158998.90       158757.27
78759       322236.36       321579.18       320921.99
78744       153444.33       153083.49       152722.64
78723       217390.33       217062.71       216735.10
78749       241718.35       241334.38       240950.42
78729       201084.43       201039.58       200994.73
78717       267401.78       266971.90       266542.03
78727       198208.55       198097.62       197986.70
78731       502081.59       500737.82       499394.06
78705       241859.45       240835.01       239810.58
78728       189319.93       189057.25       188794.57
78746       774490.51       772969.84       771449.18
78703       693138.97       690710.59       688282.20
78750       280708.77       280518.35       280327.94
78702       241930.57       241303.95       240677.33
78757       285606.49       285112.79       284619.08
78735       410985.50       409766.46       408547.42
78754       196262.62       195547.80       194832.98
78751       327895.45       326922.96       325950.46
78752       178343.33       178168.77       177994.21
78724       147987.56       147516.53       147045.50
78747       203483.65       202790.25       202096.84
78617       154060.49       153420.93       152781.37
78737       360848.73       359879.41       358910.09
78739       359962.82       359139.37       358315.93
78701       364336.65       362168.10       359999.56
78726       368899.14       367755.26       366611.37
78732       445759.64       444022.55       442285.45
78756       369375.05       368664.37       367953.70
78721       182853.26       181777.76       180702.27
78730       594651.77       592652.32       590652.86
78736       275639.41       274876.14       274112.88
78725       146884.20       146549.87       146215.54
78733       536666.00       535014.02       533362.05
78722       289561.70       288882.73       288203.76
78652       236311.77       235893.75       235475.73
78719       159172.24       158422.72       157673.20
78742       153147.25       152414.31       151681.38

04/30/2022 ($)  05/31/2022 ($)  06/30/2022 ($)
RegionName                                                
78704            1087691.0       1096965.0       1095829.0
78745             612028.0        618316.0        613862.0
78748             561694.0        568101.0        563042.0
78758             561618.0        567226.0        560180.0
78741             515889.0        519962.0        514218.0
78753             494108.0        500128.0        495392.0
78759             876764.0        884352.0        874722.0
78744             460693.0        467861.0        464934.0
78723             670097.0        672464.0        661809.0
78749             713245.0        721249.0        713630.0
78729             604083.0        608955.0        605979.0
78717             757671.0        762795.0        757874.0
78727             625102.0        633046.0        625401.0
78731            1339263.0       1353656.0       1342438.0
78705             446756.0        447351.0        442315.0
78728             546416.0        552540.0        544132.0
78746            2220266.0       2228186.0       2215378.0
78703            1783089.0       1797259.0       1786011.0
78750             795762.0        800550.0        792925.0
78702             780050.0        786733.0        779155.0
78757             816681.0        824673.0        815957.0
78735            1040835.0       1052957.0       1044929.0
78754             492827.0        499847.0        495825.0
78751             805368.0        815768.0        809571.0
78752             584701.0        590351.0        583595.0
78724             451510.0        457835.0        455704.0
78747             500830.0        505772.0        500856.0
78617             391609.0        397988.0        396445.0
78737             962569.0        969356.0        969564.0
78739             966563.0        975942.0        966675.0
78701             827659.0        834972.0        831440.0
78726             902402.0        911786.0        905356.0
78732            1027271.0       1041417.0       1038367.0
78756             952069.0        957718.0        950845.0
78721             576838.0        579854.0        570825.0
78730            1421492.0       1447688.0       1443527.0
78736             748991.0        757909.0        751814.0
78725             407091.0        415376.0        414398.0
78733            1465264.0       1487102.0       1490228.0
78722             773833.0        787315.0        779648.0
78652             624577.0        632163.0        624738.0
78719             439443.0        448147.0        443553.0
78742             441220.0        447581.0        443758.0

In [34]:
percent_change = (experimental_values_df - actual_values_df)/actual_values_df * 100
percent_change.columns = ['04/30/2022 (%)', '05/31/2022 (%)', '06/30/2022 (%)']

display(percent_change)

04/30/2022 (%)  05/31/2022 (%)  06/30/2022 (%)
78704      -64.953012      -65.361425      -65.437751
78745      -68.759076      -69.099841      -68.898865
78748      -63.524122      -63.977478      -63.696172
78758      -72.154815      -72.477455      -72.179212
78741      -64.123608      -64.564401      -64.330121
78753      -67.772121      -68.208359      -67.953203
78759      -63.247081      -63.636744      -63.311545
78744      -66.692715      -67.280134      -67.151759
78723      -67.558379      -67.721289      -67.251110
78749      -66.110053      -66.539381      -66.235946
78729      -66.712450      -66.986135      -66.831403
78717      -64.707402      -65.000832      -64.830298
78727      -68.291807      -68.707231      -68.342439
78731      -62.510605      -63.008488      -62.799469
78705      -45.863189      -46.164195      -45.782852
78728      -65.352418      -65.783970      -65.303535
78746      -65.117220      -65.309456      -65.177537
78703      -61.127068      -61.568667      -61.462600
78750      -64.724532      -64.959297      -64.646349
78702      -68.985248      -69.328355      -69.110468
78757      -65.028391      -65.427171      -65.118373
78735      -60.513866      -61.084217      -60.901897
78754      -60.176163      -60.878469      -60.705293
78751      -59.286258      -59.924518      -59.737878
78752      -69.498371      -69.819858      -69.500388
78724      -67.223858      -67.779543      -67.732234
78747      -59.370715      -59.904809      -59.649712
78617      -60.659615      -61.450865      -61.462152
78737      -62.511910      -62.874382      -62.982321
78739      -62.758473      -63.200747      -62.933154
78701      -55.979860      -56.625120      -56.701679
78726      -59.120310      -59.666494      -59.506385
78732      -56.607396      -57.363616      -57.405672
78756      -61.202912      -61.505958      -61.302452
78721      -68.300760      -68.651116      -68.343666
78730      -58.167069      -59.062152      -59.082659
78736      -63.198568      -63.732303      -63.539801
78725      -63.918583      -64.718744      -64.716157
78733      -63.374109      -64.023045      -64.209366
78722      -62.580854      -63.307859      -63.034118
78652      -62.164510      -62.684664      -62.308083
78719      -63.778638      -64.649385      -64.452230
78742      -65.290048      -65.947100      -65.818897

# **Conclusion**

### Prior to analyzing the results of the regression model, some research was done as to why Texas's real estate market stayed relatively healthy compared to the rest of the country. An article from the [Atlantic](https://www.theatlantic.com/business/archive/2010/07/how-texas-is-dominating-the-recession/60721/), *Real estate executives and economists struggled to find one reason why the Texas economy largely avoided the real estate boom and bust, but a few theories emerged. First, San Antonio Mayor Julian Castro suggested that a reliance on property taxes in Texas (compared to California) might have dulled real estate appreciation. Second, the banks that survived the Savings and Loan crisis in the 1980s have mostly held onto conservative and un-exotic lending practices. Third, land and utilities are generally cheaper throughout Texas, which holds down the cost of the living. Fourth, besides Dallas, Texas' major cities have diversified away from the kind of real estate and financial services addiction that plagued CaliFlAriVada (that's CA, FL, AZ, NV), where the recession has been the most severe.*

### It can be concluded that for this data set within this time period of December 2007 through June 2009 will be able to accurately model a potential upcoming recession or correction in the Austin housing market. As seen from the negative percent changes above, the model consistently predicted housing prices to be much lower than they actually are. This means that this 3 month span is exhibiting a much more significant drop in prices per unit time. However, it is also possible that not enough time has passed by. It is possible to speculate that with more time and data to test the models on, the decrease in housing prices in Austin may not be as severe as April 2022 - June 2022 and it, for a certain period of time, might reflect the decrease in price of the recession back in 2007-2009. 

### As a result of the incredibly inaccurate, but ironically precise, results of the regression models, for now the models cannot be reasonably used to predict the relative decrease in real estate prices in Austin for the near future. 